---
- block:
  - name: Update yum packages
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install Redis
    yum:
      name: redis
      state: present

  - name: Configure firewalld for Redis
    firewalld:
      port: 6379/tcp
      state: enabled
      permanent: true
      immediate: true

  when: ansible_os_family == "RedHat"

- block:
  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install Redis
    apt:
      name: redis-server
      state: present

  - name: Configure ufw rules for Redis
    ufw:
      rule: allow
      direction: in
      proto: tcp
      from_ip: any
      to_port: 6379

  when: ansible_os_family == "Debian"

- name: Restart Redis
  systemd:
    name: redis
    state: restarted
    daemon_reload: yes
    enabled: yes