---
- block:
  - name: Install InfluxDB repository
    copy:
      src: influxdb.repo
      dest: /etc/yum.repos.d
      mode: 0644

  - name: Update yum packages
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install InfludDB
    yum:
      name: influxdb
      state: present

  when: ansible_os_family == "RedHat"

- block:
  - name: Install the gpg public key
    apt_key:
      url: https://repos.influxdata.com/influxdb.key
      state: present

  - name: Deploy apt source file
    template:
      src: influxdb.list.j2
      dest: /etc/apt/sources.list.d/influxdb.list
      mode: 0644

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install InfludDB
    apt:
      name: influxdb

  - name: Configure ufw rules for InfluxDB
    ufw:
      rule: allow
      direction: in
      from_ip: any
      to_port: "{{ item }}"
    with_items:
      - 8086
      - 8088

  when: ansible_os_family == "Debian"

- name: Restart InfluxDB
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: yes
