---
- block:
  - name: Update yum packages
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install RabbitMQ
    yum:
      name: rabbitmq-server
      state: present

  when: ansible_os_family == "RedHat"

- block:
  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install RabbitMQ
    apt:
      name: rabbitmq-server
      state: present

  - name: Configure ufw rules for RabbitMQ
    ufw:
      rule: allow
      direction: in
      from_ip: any
      to_port: "{{ item }}"
    with_items: "{{ rabbitmq_ports }}"

  when: ansible_os_family == "Debian"