---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Java is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ java_packages }}"