---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update yum packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Update apt packages
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install the required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"