---
- name: Initialize OS setting for linux servers
  hosts: linux_servers
  become: true

  roles:
    - name: ../roles/common/packages
      tags: packages
    - name: ../roles/common/users
      tags: users